/*===========================================================================

FILE:        ul_data.c

DESCRIPTION: This file implements the target-specific NPA Bus subnodes

   Copyright (c) 2013 Qualcomm Technologies Incorporated.
             All Rights Reserved
             QUALCOMM Proprietary/GTDR
-------------------------------------------------------------------------------

$Header: //components/rel/core.adsp/2.6.1/buses/icb/src/8x10/ul_data.c#1 $ 
$DateTime: 2014/10/16 12:45:40 $
$Author: pwbldsvc $
$Change: 6781644 $

                      EDIT HISTORY FOR FILE

 Autogenerated for target: LPASS
 This file was generated using Autogen script: 
 gen.py

 when         who     what, where, why
 ----------   ---     -----------------------------------------------------------
 2013/02/05 Autogen  Autogenerated version

=============================================================================*/
#include "npa.h"
#include "npa_resource.h"
#include "npa_log.h"
#include "ul_i.h"
#include "ul_tree.h"
#include "icb_soc_data.h"

/*============================================================================
                          DEFINES
============================================================================*/
/*============================================================================
                   INTERNAL DATA DECLARATIONS
============================================================================*/
/*============================================================================
                        AXI CONFIG DECLARATIONS
============================================================================*/

/****************************************************************************/
/*                              BUSES                                       */
/****************************************************************************/
/**** Bus: bimc ****/
static HAL_bimc_InfoType bimc_hal_info =
{
  0, /* Base address */
  4800, /* QoS frequency */
};

static const char *bus_bimc_clk_names[1] =
{
  "/clk/bimc",
};

static npa_client_handle bus_bimc_clk_clients[1] = {0};

static icb_bus_def_type bimc_bus =
{
  "BIMC", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x6A000, /* HWIO region size */
  ICB_BUS_BIMC, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  (void *)&bimc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_bimc_clk_names,
  bus_bimc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
};

/**** Bus: cnoc ****/
static HAL_noc_InfoType cnoc_hal_info =
{
  0,        /* Base address */
  1,     /* Number of masters */
  0, /* Number of masters with QoS */ 
  6,      /* Number of slaves */ 
  4800,         /* QoS frequency */ 
  NULL, /* QoS master info */
};

static const char *bus_cnoc_clk_names[1] =
{
  "/clk/cnoc",
};

static npa_client_handle bus_cnoc_clk_clients[1] = {0};

static icb_bus_def_type cnoc_bus =
{
  "CONFIG_NOC", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x4000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  (void *)&cnoc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_cnoc_clk_names,
  bus_cnoc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
};

/**** Bus: pnoc ****/
static HAL_noc_InfoType pnoc_hal_info =
{
  0,        /* Base address */
  6,     /* Number of masters */
  0, /* Number of masters with QoS */ 
  7,      /* Number of slaves */ 
  4800,         /* QoS frequency */ 
  NULL, /* QoS master info */
};

static const char *bus_pnoc_clk_names[1] =
{
  "/clk/pnoc",
};

static npa_client_handle bus_pnoc_clk_clients[1] = {0};

static icb_bus_def_type pnoc_bus =
{
  "PERIPH_NOC", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x4000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  (void *)&pnoc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_pnoc_clk_names,
  bus_pnoc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
};

/**** Bus: snoc ****/
static HAL_noc_QosMasterInfoType snoc_master_info[9] =
{
  {NOC_QOS_ALLOWED_MODE_FIXED}, /* lpass_ahb */
  {0}, /* unused port 1 */
  {0}, /* unused port 2 */
  {0}, /* unused port 3 */
  {0}, /* unused port 4 */
  {0}, /* unused port 5 */
  {0}, /* unused port 6 */
  {0}, /* unused port 7 */
  {NOC_QOS_ALLOWED_MODE_FIXED}, /* periph_snoc */
};

static HAL_noc_InfoType snoc_hal_info =
{
  0,        /* Base address */
  4,     /* Number of masters */
  9, /* Number of masters with QoS */ 
  6,      /* Number of slaves */ 
  4800,         /* QoS frequency */ 
  snoc_master_info, /* QoS master info */
};

static const char *bus_snoc_clk_names[1] =
{
  "/clk/snoc",
};

static npa_client_handle bus_snoc_clk_clients[1] = {0};

static icb_bus_def_type snoc_bus =
{
  "SYSTEM_NOC", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x4000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  (void *)&snoc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_snoc_clk_names,
  bus_snoc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
};

/****************************************************************************/
/*                              SLAVES                                      */
/****************************************************************************/
/**** Slave: bimc_snoc ****/
/* slave port ids */
static uint32_t cfg_slave_bimc_snoc_ports[1] =
{
  2, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_bimc_snoc =
{
  ICBID_SLAVE_BIMC_SNOC, /* slaveId */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_bimc_snoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: blsp_1 ****/
/* slave port ids */
static uint32_t cfg_slave_blsp_1_ports[1] =
{
  5, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_blsp_1 =
{
  ICBID_SLAVE_BLSP_1, /* slaveId */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_blsp_1_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: cnoc_snoc ****/
/* slave port ids */
static uint32_t cfg_slave_cnoc_snoc_ports[1] =
{
  26, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_cnoc_snoc =
{
  ICBID_SLAVE_CNOC_SNOC, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_cnoc_snoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: ebi ****/
/* slave port ids */
static uint32_t cfg_slave_ebi_ports[1] =
{
  0, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_ebi =
{
  ICBID_SLAVE_EBI1, /* slaveId */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_ebi_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: message_ram ****/
/* slave port ids */
static uint32_t cfg_slave_message_ram_ports[1] =
{
  8, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_message_ram =
{
  ICBID_SLAVE_MESSAGE_RAM, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_message_ram_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: ocimem ****/
/* slave port ids */
static uint32_t cfg_slave_ocimem_ports[1] =
{
  10, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_ocimem =
{
  ICBID_SLAVE_OCIMEM, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_ocimem_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: ocmem ****/
/* slave port ids */
static uint32_t cfg_slave_ocmem_ports[1] =
{
  15, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_ocmem =
{
  ICBID_SLAVE_OCMEM, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_ocmem_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: pdm ****/
/* slave port ids */
static uint32_t cfg_slave_pdm_ports[1] =
{
  7, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pdm =
{
  ICBID_SLAVE_PDM, /* slaveId */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pdm_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: periph_snoc ****/
/* slave port ids */
static uint32_t cfg_slave_periph_snoc_ports[1] =
{
  11, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_periph_snoc =
{
  ICBID_SLAVE_PNOC_SNOC, /* slaveId */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_periph_snoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: pmic_arb ****/
/* slave port ids */
static uint32_t cfg_slave_pmic_arb_ports[1] =
{
  12, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pmic_arb =
{
  ICBID_SLAVE_PMIC_ARB, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pmic_arb_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: pnoc_cfg ****/
/* slave port ids */
static uint32_t cfg_slave_pnoc_cfg_ports[1] =
{
  21, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_pnoc_cfg =
{
  ICBID_SLAVE_PNOC_CFG, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_pnoc_cfg_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: prng ****/
/* slave port ids */
static uint32_t cfg_slave_prng_ports[1] =
{
  10, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_prng =
{
  ICBID_SLAVE_PRNG, /* slaveId */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_prng_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: qdss_stm ****/
/* slave port ids */
static uint32_t cfg_slave_qdss_stm_ports[1] =
{
  14, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qdss_stm =
{
  ICBID_SLAVE_QDSS_STM, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qdss_stm_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: rpm ****/
/* slave port ids */
static uint32_t cfg_slave_rpm_ports[1] =
{
  25, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_rpm =
{
  ICBID_SLAVE_RPM, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_rpm_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: sdcc_1 ****/
/* slave port ids */
static uint32_t cfg_slave_sdcc_1_ports[1] =
{
  0, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_sdcc_1 =
{
  ICBID_SLAVE_SDCC_1, /* slaveId */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_sdcc_1_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: sdcc_2 ****/
/* slave port ids */
static uint32_t cfg_slave_sdcc_2_ports[1] =
{
  2, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_sdcc_2 =
{
  ICBID_SLAVE_SDCC_2, /* slaveId */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_sdcc_2_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: snoc_bimc ****/
/* slave port ids */
static uint32_t cfg_slave_snoc_bimc_ports[1] =
{
  7, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_snoc_bimc =
{
  ICBID_SLAVE_SNOC_BIMC, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_snoc_bimc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: snoc_cnoc ****/
/* slave port ids */
static uint32_t cfg_slave_snoc_cnoc_ports[1] =
{
  9, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_snoc_cnoc =
{
  ICBID_SLAVE_SNOC_CNOC, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_snoc_cnoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: snoc_pnoc ****/
/* slave port ids */
static uint32_t cfg_slave_snoc_pnoc_ports[1] =
{
  12, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_snoc_pnoc =
{
  ICBID_SLAVE_SNOC_PNOC, /* slaveId */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_snoc_pnoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: tlmm ****/
/* slave port ids */
static uint32_t cfg_slave_tlmm_ports[1] =
{
  5, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_tlmm =
{
  ICBID_SLAVE_TLMM, /* slaveId */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_tlmm_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/**** Slave: usb_hs ****/
/* slave port ids */
static uint32_t cfg_slave_usb_hs_ports[1] =
{
  6, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_usb_hs =
{
  ICBID_SLAVE_USB_HS, /* slaveId */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_usb_hs_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
};

/****************************************************************************/
/*                              MASTERS                                     */
/****************************************************************************/
/**** Master: bimc_snoc ****/
/* master port ids */
static uint32_t cfg_master_bimc_snoc_ports[1] =
{
  3, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_bimc_snoc =
{
  ICBID_MASTER_BIMC_SNOC, /* master id */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_bimc_snoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: blsp_1 ****/
/* master port ids */
static uint32_t cfg_master_blsp_1_ports[1] =
{
  8, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_blsp_1 =
{
  ICBID_MASTER_BLSP_1, /* master id */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_blsp_1_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: cnoc_snoc ****/
/* master port ids */
static uint32_t cfg_master_cnoc_snoc_ports[1] =
{
  4, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_cnoc_snoc =
{
  ICBID_MASTER_CNOC_SNOC, /* master id */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_cnoc_snoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: lpass_ahb ****/
/* master port ids */
static uint32_t cfg_master_lpass_ahb_ports[1] =
{
  0, /* port 0 */
};

static uint32_t cfg_master_lpass_ahb_qos_ports[1] =
{
  0, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_lpass_ahb =
{
  ICBID_MASTER_LPASS_AHB, /* master id */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_lpass_ahb_ports, /* pPortIds */
  cfg_master_lpass_ahb_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: lpass_proc ****/
/* master port ids */
static uint32_t cfg_master_lpass_proc_ports[1] =
{
  4, /* port 0 */
};

static uint32_t cfg_master_lpass_proc_qos_ports[1] =
{
  4, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_lpass_proc =
{
  ICBID_MASTER_LPASS_PROC, /* master id */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_lpass_proc_ports, /* pPortIds */
  cfg_master_lpass_proc_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  10000, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: periph_snoc ****/
/* master port ids */
static uint32_t cfg_master_periph_snoc_ports[1] =
{
  10, /* port 0 */
};

static uint32_t cfg_master_periph_snoc_qos_ports[1] =
{
  8, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_periph_snoc =
{
  ICBID_MASTER_PNOC_SNOC, /* master id */
  &snoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_periph_snoc_ports, /* pPortIds */
  cfg_master_periph_snoc_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: pnoc_cfg ****/
/* master port ids */
static uint32_t cfg_master_pnoc_cfg_ports[1] =
{
  10, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_pnoc_cfg =
{
  ICBID_MASTER_PNOC_CFG, /* master id */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_pnoc_cfg_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: sdcc_1 ****/
/* master port ids */
static uint32_t cfg_master_sdcc_1_ports[1] =
{
  0, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_sdcc_1 =
{
  ICBID_MASTER_SDCC_1, /* master id */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_sdcc_1_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: sdcc_2 ****/
/* master port ids */
static uint32_t cfg_master_sdcc_2_ports[1] =
{
  2, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_sdcc_2 =
{
  ICBID_MASTER_SDCC_2, /* master id */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_sdcc_2_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: snoc_bimc ****/
/* master port ids */
static uint32_t cfg_master_snoc_bimc_ports[1] =
{
  2, /* port 0 */
};

static uint32_t cfg_master_snoc_bimc_qos_ports[1] =
{
  2, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_snoc_bimc =
{
  ICBID_MASTER_SNOC_BIMC, /* master id */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_snoc_bimc_ports, /* pPortIds */
  cfg_master_snoc_bimc_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  10000, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: snoc_cnoc ****/
/* master port ids */
static uint32_t cfg_master_snoc_cnoc_ports[1] =
{
  7, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_snoc_cnoc =
{
  ICBID_MASTER_SNOC_CNOC, /* master id */
  &cnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_snoc_cnoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: snoc_pnoc ****/
/* master port ids */
static uint32_t cfg_master_snoc_pnoc_ports[1] =
{
  11, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_snoc_pnoc =
{
  ICBID_MASTER_SNOC_PNOC, /* master id */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_snoc_pnoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/**** Master: usb_hs ****/
/* master port ids */
static uint32_t cfg_master_usb_hs_ports[1] =
{
  9, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_usb_hs =
{
  ICBID_MASTER_USB_HS, /* master id */
  &pnoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_usb_hs_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
};

/****************************************************************************/
/*                              LISTS                                       */
/****************************************************************************/
/* List of buses */
const uint32 u32cfg_bus_list_size   = 4;
icb_bus_def_type *cfg_bus_list[4] = 
{
  &bimc_bus,
  &cnoc_bus,
  &pnoc_bus,
  &snoc_bus,
};

/* List of slaves */
const uint32 u32cfg_slave_list_size   = 21;
icb_slave_def_type *cfg_slave_list[21] = 
{
  &cfg_slave_bimc_snoc,
  &cfg_slave_blsp_1,
  &cfg_slave_cnoc_snoc,
  &cfg_slave_ebi,
  &cfg_slave_message_ram,
  &cfg_slave_ocimem,
  &cfg_slave_ocmem,
  &cfg_slave_pdm,
  &cfg_slave_periph_snoc,
  &cfg_slave_pmic_arb,
  &cfg_slave_pnoc_cfg,
  &cfg_slave_prng,
  &cfg_slave_qdss_stm,
  &cfg_slave_rpm,
  &cfg_slave_sdcc_1,
  &cfg_slave_sdcc_2,
  &cfg_slave_snoc_bimc,
  &cfg_slave_snoc_cnoc,
  &cfg_slave_snoc_pnoc,
  &cfg_slave_tlmm,
  &cfg_slave_usb_hs,
};

/* List of masters */
const uint32 u32cfg_master_list_size   = 13;
icb_master_def_type *cfg_master_list[13] = 
{
  &cfg_master_bimc_snoc,
  &cfg_master_blsp_1,
  &cfg_master_cnoc_snoc,
  &cfg_master_lpass_ahb,
  &cfg_master_lpass_proc,
  &cfg_master_periph_snoc,
  &cfg_master_pnoc_cfg,
  &cfg_master_sdcc_1,
  &cfg_master_sdcc_2,
  &cfg_master_snoc_bimc,
  &cfg_master_snoc_cnoc,
  &cfg_master_snoc_pnoc,
  &cfg_master_usb_hs,
};

/* List of configuration clocks */
const uint32 u32ul_cfg_clk_node_list_size   = 4;
const char *ul_cfg_clock_node_list[] =
{
  "/clk/bimc",
  "/clk/cnoc",
  "/clk/pnoc",
  "/clk/snoc",
};

/*============================================================================
                        TOPOLOGY ROUTE DECLARATIONS
============================================================================*/

/*****************************************************/
/*                       bimc                                      */
/*****************************************************/
/* Masters */
/* SNOC_BIMC */
static ul_clock_type master_snoc_bimc_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_snoc_bimc =
{
  /* Master Data */
  "/icb/master/snoc_bimc",
  ICBID_MASTER_SNOC_BIMC,                   /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_snoc_bimc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_snoc_bimc,
    NULL,
  },
  &cfg_master_snoc_bimc 
};

/* LPASS_PROC */
static ul_clock_type master_lpass_proc_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_lpass_proc =
{
  /* Master Data */
  "/icb/master/lpass_proc",
  ICBID_MASTER_LPASS_PROC,                  /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_lpass_proc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_lpass_proc,
    NULL,
  },
  &cfg_master_lpass_proc 
};

/* Slaves */
/* EBI */
static ul_clock_type slave_ebi_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_ebi =
{
  /* Slave Data */
  "/icb/slave/ebi",
  ICBID_SLAVE_EBI1,                        /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_ebi_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_ebi,
    NULL,
  },
  &cfg_slave_ebi
};

/* BIMC_SNOC */
static ul_clock_type slave_bimc_snoc_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_bimc_snoc =
{
  /* Slave Data */
  "/icb/slave/bimc_snoc",
  ICBID_SLAVE_BIMC_SNOC,                   /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_bimc_snoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_bimc_snoc,
    NULL,
  },
  &cfg_slave_bimc_snoc
};

/*****************************************************/
/*                       cnoc                                      */
/*****************************************************/
/* Masters */
/* SNOC_CNOC */
static ul_clock_type master_snoc_cnoc_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_snoc_cnoc =
{
  /* Master Data */
  "/icb/master/snoc_cnoc",
  ICBID_MASTER_SNOC_CNOC,                   /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_snoc_cnoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_snoc_cnoc,
    NULL,
  },
  &cfg_master_snoc_cnoc 
};

/* Slaves */
/* TLMM */
static ul_clock_type slave_tlmm_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_tlmm =
{
  /* Slave Data */
  "/icb/slave/tlmm",
  ICBID_SLAVE_TLMM,                        /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_tlmm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_tlmm,
    NULL,
  },
  &cfg_slave_tlmm
};

/* MESSAGE_RAM */
static ul_clock_type slave_message_ram_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_message_ram =
{
  /* Slave Data */
  "/icb/slave/message_ram",
  ICBID_SLAVE_MESSAGE_RAM,                 /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_message_ram_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_message_ram,
    NULL,
  },
  &cfg_slave_message_ram
};

/* PMIC_ARB */
static ul_clock_type slave_pmic_arb_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pmic_arb =
{
  /* Slave Data */
  "/icb/slave/pmic_arb",
  ICBID_SLAVE_PMIC_ARB,                    /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pmic_arb_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_pmic_arb,
    NULL,
  },
  &cfg_slave_pmic_arb
};

/* PNOC_CFG */
static ul_clock_type slave_pnoc_cfg_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pnoc_cfg =
{
  /* Slave Data */
  "/icb/slave/pnoc_cfg",
  ICBID_SLAVE_PNOC_CFG,                    /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pnoc_cfg_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_pnoc_cfg,
    NULL,
  },
  &cfg_slave_pnoc_cfg
};

/* RPM */
static ul_clock_type slave_rpm_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_rpm =
{
  /* Slave Data */
  "/icb/slave/rpm",
  ICBID_SLAVE_RPM,                         /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_rpm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_rpm,
    NULL,
  },
  &cfg_slave_rpm
};

/* CNOC_SNOC */
static ul_clock_type slave_cnoc_snoc_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_cnoc_snoc =
{
  /* Slave Data */
  "/icb/slave/cnoc_snoc",
  ICBID_SLAVE_CNOC_SNOC,                   /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_cnoc_snoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_cnoc_snoc,
    NULL,
  },
  &cfg_slave_cnoc_snoc
};

/*****************************************************/
/*                       pnoc                                      */
/*****************************************************/
/* Masters */
/* SDCC_1 */
static ul_clock_type master_sdcc_1_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_sdcc_1 =
{
  /* Master Data */
  "/icb/master/sdcc_1",
  ICBID_MASTER_SDCC_1,                      /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_sdcc_1_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_sdcc_1,
    NULL,
  },
  &cfg_master_sdcc_1 
};

/* SDCC_2 */
static ul_clock_type master_sdcc_2_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_sdcc_2 =
{
  /* Master Data */
  "/icb/master/sdcc_2",
  ICBID_MASTER_SDCC_2,                      /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_sdcc_2_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_sdcc_2,
    NULL,
  },
  &cfg_master_sdcc_2 
};

/* BLSP_1 */
static ul_clock_type master_blsp_1_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_blsp_1 =
{
  /* Master Data */
  "/icb/master/blsp_1",
  ICBID_MASTER_BLSP_1,                      /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_blsp_1_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_blsp_1,
    NULL,
  },
  &cfg_master_blsp_1 
};

/* USB_HS */
static ul_clock_type master_usb_hs_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_usb_hs =
{
  /* Master Data */
  "/icb/master/usb_hs",
  ICBID_MASTER_USB_HS,                      /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_usb_hs_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_usb_hs,
    NULL,
  },
  &cfg_master_usb_hs 
};

/* PNOC_CFG */
static ul_clock_type master_pnoc_cfg_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_pnoc_cfg =
{
  /* Master Data */
  "/icb/master/pnoc_cfg",
  ICBID_MASTER_PNOC_CFG,                    /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_pnoc_cfg_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_pnoc_cfg,
    NULL,
  },
  &cfg_master_pnoc_cfg 
};

/* SNOC_PNOC */
static ul_clock_type master_snoc_pnoc_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_snoc_pnoc =
{
  /* Master Data */
  "/icb/master/snoc_pnoc",
  ICBID_MASTER_SNOC_PNOC,                   /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_snoc_pnoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_snoc_pnoc,
    NULL,
  },
  &cfg_master_snoc_pnoc 
};

/* Slaves */
/* SDCC_1 */
static ul_clock_type slave_sdcc_1_slv_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_sdcc_1 =
{
  /* Slave Data */
  "/icb/slave/sdcc_1",
  ICBID_SLAVE_SDCC_1,                      /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_sdcc_1_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_sdcc_1,
    NULL,
  },
  &cfg_slave_sdcc_1
};

/* SDCC_2 */
static ul_clock_type slave_sdcc_2_slv_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_sdcc_2 =
{
  /* Slave Data */
  "/icb/slave/sdcc_2",
  ICBID_SLAVE_SDCC_2,                      /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_sdcc_2_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_sdcc_2,
    NULL,
  },
  &cfg_slave_sdcc_2
};

/* BLSP_1 */
static ul_clock_type slave_blsp_1_slv_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_blsp_1 =
{
  /* Slave Data */
  "/icb/slave/blsp_1",
  ICBID_SLAVE_BLSP_1,                      /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_blsp_1_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_blsp_1,
    NULL,
  },
  &cfg_slave_blsp_1
};

/* USB_HS */
static ul_clock_type slave_usb_hs_slv_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_usb_hs =
{
  /* Slave Data */
  "/icb/slave/usb_hs",
  ICBID_SLAVE_USB_HS,                      /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_usb_hs_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_usb_hs,
    NULL,
  },
  &cfg_slave_usb_hs
};

/* PDM */
static ul_clock_type slave_pdm_slv_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_pdm =
{
  /* Slave Data */
  "/icb/slave/pdm",
  ICBID_SLAVE_PDM,                         /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_pdm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_pdm,
    NULL,
  },
  &cfg_slave_pdm
};

/* PRNG */
static ul_clock_type slave_prng_slv_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_prng =
{
  /* Slave Data */
  "/icb/slave/prng",
  ICBID_SLAVE_PRNG,                        /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_prng_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_prng,
    NULL,
  },
  &cfg_slave_prng
};

/* PERIPH_SNOC */
static ul_clock_type slave_periph_snoc_slv_clks[1] =
{
  {
    "/clk/pnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_periph_snoc =
{
  /* Slave Data */
  "/icb/slave/periph_snoc",
  ICBID_SLAVE_PNOC_SNOC,                   /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_periph_snoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_periph_snoc,
    NULL,
  },
  &cfg_slave_periph_snoc
};

/*****************************************************/
/*                       snoc                                      */
/*****************************************************/
/* Masters */
/* LPASS_AHB */
static ul_clock_type master_lpass_ahb_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_lpass_ahb =
{
  /* Master Data */
  "/icb/master/lpass_ahb",
  ICBID_MASTER_LPASS_AHB,                   /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_lpass_ahb_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_lpass_ahb,
    NULL,
  },
  &cfg_master_lpass_ahb 
};

/* BIMC_SNOC */
static ul_clock_type master_bimc_snoc_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_bimc_snoc =
{
  /* Master Data */
  "/icb/master/bimc_snoc",
  ICBID_MASTER_BIMC_SNOC,                   /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_bimc_snoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_bimc_snoc,
    NULL,
  },
  &cfg_master_bimc_snoc 
};

/* CNOC_SNOC */
static ul_clock_type master_cnoc_snoc_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_cnoc_snoc =
{
  /* Master Data */
  "/icb/master/cnoc_snoc",
  ICBID_MASTER_CNOC_SNOC,                   /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_cnoc_snoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_cnoc_snoc,
    NULL,
  },
  &cfg_master_cnoc_snoc 
};

/* PERIPH_SNOC */
static ul_clock_type master_periph_snoc_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_periph_snoc =
{
  /* Master Data */
  "/icb/master/periph_snoc",
  ICBID_MASTER_PNOC_SNOC,                   /* External Master ID */
  8,                                       /* bus width in bytes */
  1,
  master_periph_snoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_master_data_type),
    &master_periph_snoc,
    NULL,
  },
  &cfg_master_periph_snoc 
};

/* Slaves */
/* SNOC_BIMC */
static ul_clock_type slave_snoc_bimc_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_snoc_bimc =
{
  /* Slave Data */
  "/icb/slave/snoc_bimc",
  ICBID_SLAVE_SNOC_BIMC,                   /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_snoc_bimc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_snoc_bimc,
    NULL,
  },
  &cfg_slave_snoc_bimc
};

/* SNOC_CNOC */
static ul_clock_type slave_snoc_cnoc_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_snoc_cnoc =
{
  /* Slave Data */
  "/icb/slave/snoc_cnoc",
  ICBID_SLAVE_SNOC_CNOC,                   /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_snoc_cnoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_snoc_cnoc,
    NULL,
  },
  &cfg_slave_snoc_cnoc
};

/* OCIMEM */
static ul_clock_type slave_ocimem_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_ocimem =
{
  /* Slave Data */
  "/icb/slave/ocimem",
  ICBID_SLAVE_OCIMEM,                      /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_ocimem_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_ocimem,
    NULL,
  },
  &cfg_slave_ocimem
};

/* SNOC_PNOC */
static ul_clock_type slave_snoc_pnoc_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_snoc_pnoc =
{
  /* Slave Data */
  "/icb/slave/snoc_pnoc",
  ICBID_SLAVE_SNOC_PNOC,                   /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_snoc_pnoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_snoc_pnoc,
    NULL,
  },
  &cfg_slave_snoc_pnoc
};

/* QDSS_STM */
static ul_clock_type slave_qdss_stm_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qdss_stm =
{
  /* Slave Data */
  "/icb/slave/qdss_stm",
  ICBID_SLAVE_QDSS_STM,                    /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qdss_stm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_qdss_stm,
    NULL,
  },
  &cfg_slave_qdss_stm
};

/* OCMEM */
static ul_clock_type slave_ocmem_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_ocmem =
{
  /* Slave Data */
  "/icb/slave/ocmem",
  ICBID_SLAVE_OCMEM,                       /* External Slave ID */
  8,                                       /* bus width in bytes */
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_ocmem_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    sizeof(ul_slave_data_type),
    &slave_ocmem,
    NULL,
  },
  &cfg_slave_ocmem
};

/* Define the valid routes  */
static ul_pair_type route_blsp_1_ebi_list_array[3] =
{
  {
    &master_blsp_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_blsp_1_ebi_list =
{
  3,
  route_blsp_1_ebi_list_array
};
static ul_pair_type route_blsp_1_message_ram_list_array[3] =
{
  {
    &master_blsp_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_message_ram
  },
};
static ul_route_list_type route_blsp_1_message_ram_list =
{
  3,
  route_blsp_1_message_ram_list_array
};
static ul_pair_type route_blsp_1_ocimem_list_array[2] =
{
  {
    &master_blsp_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_ocimem
  },
};
static ul_route_list_type route_blsp_1_ocimem_list =
{
  2,
  route_blsp_1_ocimem_list_array
};
static ul_pair_type route_blsp_1_pmic_arb_list_array[3] =
{
  {
    &master_blsp_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_pmic_arb
  },
};
static ul_route_list_type route_blsp_1_pmic_arb_list =
{
  3,
  route_blsp_1_pmic_arb_list_array
};
static ul_pair_type route_blsp_1_qdss_stm_list_array[2] =
{
  {
    &master_blsp_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_blsp_1_qdss_stm_list =
{
  2,
  route_blsp_1_qdss_stm_list_array
};
static ul_pair_type route_blsp_1_rpm_list_array[3] =
{
  {
    &master_blsp_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_rpm
  },
};
static ul_route_list_type route_blsp_1_rpm_list =
{
  3,
  route_blsp_1_rpm_list_array
};
static ul_pair_type route_blsp_1_sdcc_1_list_array[1] =
{
  {
    &master_blsp_1,
    &slave_sdcc_1
  },
};
static ul_route_list_type route_blsp_1_sdcc_1_list =
{
  1,
  route_blsp_1_sdcc_1_list_array
};
static ul_pair_type route_blsp_1_sdcc_2_list_array[1] =
{
  {
    &master_blsp_1,
    &slave_sdcc_2
  },
};
static ul_route_list_type route_blsp_1_sdcc_2_list =
{
  1,
  route_blsp_1_sdcc_2_list_array
};
static ul_pair_type route_blsp_1_tlmm_list_array[3] =
{
  {
    &master_blsp_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm
  },
};
static ul_route_list_type route_blsp_1_tlmm_list =
{
  3,
  route_blsp_1_tlmm_list_array
};
static ul_pair_type route_blsp_1_usb_hs_list_array[1] =
{
  {
    &master_blsp_1,
    &slave_usb_hs
  },
};
static ul_route_list_type route_blsp_1_usb_hs_list =
{
  1,
  route_blsp_1_usb_hs_list_array
};
static ul_pair_type route_lpass_ahb_blsp_1_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_blsp_1
  },
};
static ul_route_list_type route_lpass_ahb_blsp_1_list =
{
  2,
  route_lpass_ahb_blsp_1_list_array
};
static ul_pair_type route_lpass_ahb_ebi_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_lpass_ahb_ebi_list =
{
  2,
  route_lpass_ahb_ebi_list_array
};
static ul_pair_type route_lpass_ahb_ocimem_list_array[1] =
{
  {
    &master_lpass_ahb,
    &slave_ocimem
  },
};
static ul_route_list_type route_lpass_ahb_ocimem_list =
{
  1,
  route_lpass_ahb_ocimem_list_array
};
static ul_pair_type route_lpass_ahb_pdm_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_pdm
  },
};
static ul_route_list_type route_lpass_ahb_pdm_list =
{
  2,
  route_lpass_ahb_pdm_list_array
};
static ul_pair_type route_lpass_ahb_prng_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_prng
  },
};
static ul_route_list_type route_lpass_ahb_prng_list =
{
  2,
  route_lpass_ahb_prng_list_array
};
static ul_pair_type route_lpass_ahb_sdcc_1_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_sdcc_1
  },
};
static ul_route_list_type route_lpass_ahb_sdcc_1_list =
{
  2,
  route_lpass_ahb_sdcc_1_list_array
};
static ul_pair_type route_lpass_ahb_sdcc_2_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_sdcc_2
  },
};
static ul_route_list_type route_lpass_ahb_sdcc_2_list =
{
  2,
  route_lpass_ahb_sdcc_2_list_array
};
static ul_pair_type route_lpass_ahb_usb_hs_list_array[2] =
{
  {
    &master_lpass_ahb,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_usb_hs
  },
};
static ul_route_list_type route_lpass_ahb_usb_hs_list =
{
  2,
  route_lpass_ahb_usb_hs_list_array
};
static ul_pair_type route_lpass_proc_blsp_1_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_blsp_1
  },
};
static ul_route_list_type route_lpass_proc_blsp_1_list =
{
  3,
  route_lpass_proc_blsp_1_list_array
};
static ul_pair_type route_lpass_proc_ebi_list_array[1] =
{
  {
    &master_lpass_proc,
    &slave_ebi
  },
};
static ul_route_list_type route_lpass_proc_ebi_list =
{
  1,
  route_lpass_proc_ebi_list_array
};
static ul_pair_type route_lpass_proc_message_ram_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_message_ram
  },
};
static ul_route_list_type route_lpass_proc_message_ram_list =
{
  3,
  route_lpass_proc_message_ram_list_array
};
static ul_pair_type route_lpass_proc_ocimem_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_ocimem
  },
};
static ul_route_list_type route_lpass_proc_ocimem_list =
{
  2,
  route_lpass_proc_ocimem_list_array
};
static ul_pair_type route_lpass_proc_ocmem_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_ocmem
  },
};
static ul_route_list_type route_lpass_proc_ocmem_list =
{
  2,
  route_lpass_proc_ocmem_list_array
};
static ul_pair_type route_lpass_proc_pdm_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_pdm
  },
};
static ul_route_list_type route_lpass_proc_pdm_list =
{
  3,
  route_lpass_proc_pdm_list_array
};
static ul_pair_type route_lpass_proc_pmic_arb_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_pmic_arb
  },
};
static ul_route_list_type route_lpass_proc_pmic_arb_list =
{
  3,
  route_lpass_proc_pmic_arb_list_array
};
static ul_pair_type route_lpass_proc_prng_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_prng
  },
};
static ul_route_list_type route_lpass_proc_prng_list =
{
  3,
  route_lpass_proc_prng_list_array
};
static ul_pair_type route_lpass_proc_qdss_stm_list_array[2] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_lpass_proc_qdss_stm_list =
{
  2,
  route_lpass_proc_qdss_stm_list_array
};
static ul_pair_type route_lpass_proc_rpm_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_rpm
  },
};
static ul_route_list_type route_lpass_proc_rpm_list =
{
  3,
  route_lpass_proc_rpm_list_array
};
static ul_pair_type route_lpass_proc_sdcc_1_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_sdcc_1
  },
};
static ul_route_list_type route_lpass_proc_sdcc_1_list =
{
  3,
  route_lpass_proc_sdcc_1_list_array
};
static ul_pair_type route_lpass_proc_sdcc_2_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_sdcc_2
  },
};
static ul_route_list_type route_lpass_proc_sdcc_2_list =
{
  3,
  route_lpass_proc_sdcc_2_list_array
};
static ul_pair_type route_lpass_proc_tlmm_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm
  },
};
static ul_route_list_type route_lpass_proc_tlmm_list =
{
  3,
  route_lpass_proc_tlmm_list_array
};
static ul_pair_type route_lpass_proc_usb_hs_list_array[3] =
{
  {
    &master_lpass_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_pnoc
  },
  {
    &master_snoc_pnoc,
    &slave_usb_hs
  },
};
static ul_route_list_type route_lpass_proc_usb_hs_list =
{
  3,
  route_lpass_proc_usb_hs_list_array
};
static ul_pair_type route_sdcc_1_blsp_1_list_array[1] =
{
  {
    &master_sdcc_1,
    &slave_blsp_1
  },
};
static ul_route_list_type route_sdcc_1_blsp_1_list =
{
  1,
  route_sdcc_1_blsp_1_list_array
};
static ul_pair_type route_sdcc_1_ebi_list_array[3] =
{
  {
    &master_sdcc_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_sdcc_1_ebi_list =
{
  3,
  route_sdcc_1_ebi_list_array
};
static ul_pair_type route_sdcc_1_message_ram_list_array[3] =
{
  {
    &master_sdcc_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_message_ram
  },
};
static ul_route_list_type route_sdcc_1_message_ram_list =
{
  3,
  route_sdcc_1_message_ram_list_array
};
static ul_pair_type route_sdcc_1_ocimem_list_array[2] =
{
  {
    &master_sdcc_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_ocimem
  },
};
static ul_route_list_type route_sdcc_1_ocimem_list =
{
  2,
  route_sdcc_1_ocimem_list_array
};
static ul_pair_type route_sdcc_1_pmic_arb_list_array[3] =
{
  {
    &master_sdcc_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_pmic_arb
  },
};
static ul_route_list_type route_sdcc_1_pmic_arb_list =
{
  3,
  route_sdcc_1_pmic_arb_list_array
};
static ul_pair_type route_sdcc_1_qdss_stm_list_array[2] =
{
  {
    &master_sdcc_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_sdcc_1_qdss_stm_list =
{
  2,
  route_sdcc_1_qdss_stm_list_array
};
static ul_pair_type route_sdcc_1_rpm_list_array[3] =
{
  {
    &master_sdcc_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_rpm
  },
};
static ul_route_list_type route_sdcc_1_rpm_list =
{
  3,
  route_sdcc_1_rpm_list_array
};
static ul_pair_type route_sdcc_1_sdcc_2_list_array[1] =
{
  {
    &master_sdcc_1,
    &slave_sdcc_2
  },
};
static ul_route_list_type route_sdcc_1_sdcc_2_list =
{
  1,
  route_sdcc_1_sdcc_2_list_array
};
static ul_pair_type route_sdcc_1_tlmm_list_array[3] =
{
  {
    &master_sdcc_1,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm
  },
};
static ul_route_list_type route_sdcc_1_tlmm_list =
{
  3,
  route_sdcc_1_tlmm_list_array
};
static ul_pair_type route_sdcc_1_usb_hs_list_array[1] =
{
  {
    &master_sdcc_1,
    &slave_usb_hs
  },
};
static ul_route_list_type route_sdcc_1_usb_hs_list =
{
  1,
  route_sdcc_1_usb_hs_list_array
};
static ul_pair_type route_sdcc_2_blsp_1_list_array[1] =
{
  {
    &master_sdcc_2,
    &slave_blsp_1
  },
};
static ul_route_list_type route_sdcc_2_blsp_1_list =
{
  1,
  route_sdcc_2_blsp_1_list_array
};
static ul_pair_type route_sdcc_2_ebi_list_array[3] =
{
  {
    &master_sdcc_2,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_sdcc_2_ebi_list =
{
  3,
  route_sdcc_2_ebi_list_array
};
static ul_pair_type route_sdcc_2_message_ram_list_array[3] =
{
  {
    &master_sdcc_2,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_message_ram
  },
};
static ul_route_list_type route_sdcc_2_message_ram_list =
{
  3,
  route_sdcc_2_message_ram_list_array
};
static ul_pair_type route_sdcc_2_ocimem_list_array[2] =
{
  {
    &master_sdcc_2,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_ocimem
  },
};
static ul_route_list_type route_sdcc_2_ocimem_list =
{
  2,
  route_sdcc_2_ocimem_list_array
};
static ul_pair_type route_sdcc_2_pmic_arb_list_array[3] =
{
  {
    &master_sdcc_2,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_pmic_arb
  },
};
static ul_route_list_type route_sdcc_2_pmic_arb_list =
{
  3,
  route_sdcc_2_pmic_arb_list_array
};
static ul_pair_type route_sdcc_2_qdss_stm_list_array[2] =
{
  {
    &master_sdcc_2,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_sdcc_2_qdss_stm_list =
{
  2,
  route_sdcc_2_qdss_stm_list_array
};
static ul_pair_type route_sdcc_2_rpm_list_array[3] =
{
  {
    &master_sdcc_2,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_rpm
  },
};
static ul_route_list_type route_sdcc_2_rpm_list =
{
  3,
  route_sdcc_2_rpm_list_array
};
static ul_pair_type route_sdcc_2_sdcc_1_list_array[1] =
{
  {
    &master_sdcc_2,
    &slave_sdcc_1
  },
};
static ul_route_list_type route_sdcc_2_sdcc_1_list =
{
  1,
  route_sdcc_2_sdcc_1_list_array
};
static ul_pair_type route_sdcc_2_tlmm_list_array[3] =
{
  {
    &master_sdcc_2,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm
  },
};
static ul_route_list_type route_sdcc_2_tlmm_list =
{
  3,
  route_sdcc_2_tlmm_list_array
};
static ul_pair_type route_sdcc_2_usb_hs_list_array[1] =
{
  {
    &master_sdcc_2,
    &slave_usb_hs
  },
};
static ul_route_list_type route_sdcc_2_usb_hs_list =
{
  1,
  route_sdcc_2_usb_hs_list_array
};
static ul_pair_type route_usb_hs_blsp_1_list_array[1] =
{
  {
    &master_usb_hs,
    &slave_blsp_1
  },
};
static ul_route_list_type route_usb_hs_blsp_1_list =
{
  1,
  route_usb_hs_blsp_1_list_array
};
static ul_pair_type route_usb_hs_ebi_list_array[3] =
{
  {
    &master_usb_hs,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_usb_hs_ebi_list =
{
  3,
  route_usb_hs_ebi_list_array
};
static ul_pair_type route_usb_hs_message_ram_list_array[3] =
{
  {
    &master_usb_hs,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_message_ram
  },
};
static ul_route_list_type route_usb_hs_message_ram_list =
{
  3,
  route_usb_hs_message_ram_list_array
};
static ul_pair_type route_usb_hs_ocimem_list_array[2] =
{
  {
    &master_usb_hs,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_ocimem
  },
};
static ul_route_list_type route_usb_hs_ocimem_list =
{
  2,
  route_usb_hs_ocimem_list_array
};
static ul_pair_type route_usb_hs_pmic_arb_list_array[3] =
{
  {
    &master_usb_hs,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_pmic_arb
  },
};
static ul_route_list_type route_usb_hs_pmic_arb_list =
{
  3,
  route_usb_hs_pmic_arb_list_array
};
static ul_pair_type route_usb_hs_qdss_stm_list_array[2] =
{
  {
    &master_usb_hs,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_qdss_stm
  },
};
static ul_route_list_type route_usb_hs_qdss_stm_list =
{
  2,
  route_usb_hs_qdss_stm_list_array
};
static ul_pair_type route_usb_hs_rpm_list_array[3] =
{
  {
    &master_usb_hs,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_rpm
  },
};
static ul_route_list_type route_usb_hs_rpm_list =
{
  3,
  route_usb_hs_rpm_list_array
};
static ul_pair_type route_usb_hs_sdcc_1_list_array[1] =
{
  {
    &master_usb_hs,
    &slave_sdcc_1
  },
};
static ul_route_list_type route_usb_hs_sdcc_1_list =
{
  1,
  route_usb_hs_sdcc_1_list_array
};
static ul_pair_type route_usb_hs_sdcc_2_list_array[1] =
{
  {
    &master_usb_hs,
    &slave_sdcc_2
  },
};
static ul_route_list_type route_usb_hs_sdcc_2_list =
{
  1,
  route_usb_hs_sdcc_2_list_array
};
static ul_pair_type route_usb_hs_tlmm_list_array[3] =
{
  {
    &master_usb_hs,
    &slave_periph_snoc
  },
  {
    &master_periph_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_tlmm
  },
};
static ul_route_list_type route_usb_hs_tlmm_list =
{
  3,
  route_usb_hs_tlmm_list_array
};

/*============================================================================
                                 ROUTE TREE
============================================================================*/
/* Forward declarations */
static ul_treeNodeType route_0x1200000000L_lpass_ahb_ebi_node;
static ul_treeNodeType route_0x120000001aL_lpass_ahb_ocimem_node;
static ul_treeNodeType route_0x120000001fL_lpass_ahb_sdcc_1_node;
static ul_treeNodeType route_0x1200000021L_lpass_ahb_sdcc_2_node;
static ul_treeNodeType route_0x1200000027L_lpass_ahb_blsp_1_node;
static ul_treeNodeType route_0x1200000028L_lpass_ahb_usb_hs_node;
static ul_treeNodeType route_0x1200000029L_lpass_ahb_pdm_node;
static ul_treeNodeType route_0x120000002cL_lpass_ahb_prng_node;
static ul_treeNodeType route_0x1900000000L_lpass_proc_ebi_node;
static ul_treeNodeType route_0x1900000012L_lpass_proc_ocmem_node;
static ul_treeNodeType route_0x190000001aL_lpass_proc_ocimem_node;
static ul_treeNodeType route_0x190000001eL_lpass_proc_qdss_stm_node;
static ul_treeNodeType route_0x190000001fL_lpass_proc_sdcc_1_node;
static ul_treeNodeType route_0x1900000021L_lpass_proc_sdcc_2_node;
static ul_treeNodeType route_0x1900000027L_lpass_proc_blsp_1_node;
static ul_treeNodeType route_0x1900000028L_lpass_proc_usb_hs_node;
static ul_treeNodeType route_0x1900000029L_lpass_proc_pdm_node;
static ul_treeNodeType route_0x190000002cL_lpass_proc_prng_node;
static ul_treeNodeType route_0x1900000033L_lpass_proc_tlmm_node;
static ul_treeNodeType route_0x1900000037L_lpass_proc_message_ram_node;
static ul_treeNodeType route_0x190000003bL_lpass_proc_pmic_arb_node;
static ul_treeNodeType route_0x190000004aL_lpass_proc_rpm_node;
static ul_treeNodeType route_0x2100000000L_sdcc_1_ebi_node;
static ul_treeNodeType route_0x210000001aL_sdcc_1_ocimem_node;
static ul_treeNodeType route_0x210000001eL_sdcc_1_qdss_stm_node;
static ul_treeNodeType route_0x2100000021L_sdcc_1_sdcc_2_node;
static ul_treeNodeType route_0x2100000027L_sdcc_1_blsp_1_node;
static ul_treeNodeType route_0x2100000028L_sdcc_1_usb_hs_node;
static ul_treeNodeType route_0x2100000033L_sdcc_1_tlmm_node;
static ul_treeNodeType route_0x2100000037L_sdcc_1_message_ram_node;
static ul_treeNodeType route_0x210000003bL_sdcc_1_pmic_arb_node;
static ul_treeNodeType route_0x210000004aL_sdcc_1_rpm_node;
static ul_treeNodeType route_0x2300000000L_sdcc_2_ebi_node;
static ul_treeNodeType route_0x230000001aL_sdcc_2_ocimem_node;
static ul_treeNodeType route_0x230000001eL_sdcc_2_qdss_stm_node;
static ul_treeNodeType route_0x230000001fL_sdcc_2_sdcc_1_node;
static ul_treeNodeType route_0x2300000027L_sdcc_2_blsp_1_node;
static ul_treeNodeType route_0x2300000028L_sdcc_2_usb_hs_node;
static ul_treeNodeType route_0x2300000033L_sdcc_2_tlmm_node;
static ul_treeNodeType route_0x2300000037L_sdcc_2_message_ram_node;
static ul_treeNodeType route_0x230000003bL_sdcc_2_pmic_arb_node;
static ul_treeNodeType route_0x230000004aL_sdcc_2_rpm_node;
static ul_treeNodeType route_0x2900000000L_blsp_1_ebi_node;
static ul_treeNodeType route_0x290000001aL_blsp_1_ocimem_node;
static ul_treeNodeType route_0x290000001eL_blsp_1_qdss_stm_node;
static ul_treeNodeType route_0x290000001fL_blsp_1_sdcc_1_node;
static ul_treeNodeType route_0x2900000021L_blsp_1_sdcc_2_node;
static ul_treeNodeType route_0x2900000028L_blsp_1_usb_hs_node;
static ul_treeNodeType route_0x2900000033L_blsp_1_tlmm_node;
static ul_treeNodeType route_0x2900000037L_blsp_1_message_ram_node;
static ul_treeNodeType route_0x290000003bL_blsp_1_pmic_arb_node;
static ul_treeNodeType route_0x290000004aL_blsp_1_rpm_node;
static ul_treeNodeType route_0x2a00000000L_usb_hs_ebi_node;
static ul_treeNodeType route_0x2a0000001aL_usb_hs_ocimem_node;
static ul_treeNodeType route_0x2a0000001eL_usb_hs_qdss_stm_node;
static ul_treeNodeType route_0x2a0000001fL_usb_hs_sdcc_1_node;
static ul_treeNodeType route_0x2a00000021L_usb_hs_sdcc_2_node;
static ul_treeNodeType route_0x2a00000027L_usb_hs_blsp_1_node;
static ul_treeNodeType route_0x2a00000033L_usb_hs_tlmm_node;
static ul_treeNodeType route_0x2a00000037L_usb_hs_message_ram_node;
static ul_treeNodeType route_0x2a0000003bL_usb_hs_pmic_arb_node;
static ul_treeNodeType route_0x2a0000004aL_usb_hs_rpm_node;

/* Create the tree */
static ul_treeNodeType route_0x1200000000L_lpass_ahb_ebi_node =
{
  0x1200000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x120000001aL_lpass_ahb_ocimem_node =
{
  0x120000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_ocimem_list,
  &route_0x1200000000L_lpass_ahb_ebi_node,
  &route_0x120000001fL_lpass_ahb_sdcc_1_node
};
static ul_treeNodeType route_0x120000001fL_lpass_ahb_sdcc_1_node =
{
  0x120000001fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_sdcc_1_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1200000021L_lpass_ahb_sdcc_2_node =
{
  0x1200000021ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_sdcc_2_list,
  &route_0x120000001aL_lpass_ahb_ocimem_node,
  &route_0x1200000028L_lpass_ahb_usb_hs_node
};
static ul_treeNodeType route_0x1200000027L_lpass_ahb_blsp_1_node =
{
  0x1200000027ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_blsp_1_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1200000028L_lpass_ahb_usb_hs_node =
{
  0x1200000028ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_usb_hs_list,
  &route_0x1200000027L_lpass_ahb_blsp_1_node,
  &route_0x1200000029L_lpass_ahb_pdm_node
};
static ul_treeNodeType route_0x1200000029L_lpass_ahb_pdm_node =
{
  0x1200000029ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_pdm_list,
  NULL,
  &route_0x120000002cL_lpass_ahb_prng_node
};
static ul_treeNodeType route_0x120000002cL_lpass_ahb_prng_node =
{
  0x120000002cULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_ahb_prng_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1900000000L_lpass_proc_ebi_node =
{
  0x1900000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_ebi_list,
  &route_0x1200000021L_lpass_ahb_sdcc_2_node,
  &route_0x1900000029L_lpass_proc_pdm_node
};
static ul_treeNodeType route_0x1900000012L_lpass_proc_ocmem_node =
{
  0x1900000012ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_ocmem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x190000001aL_lpass_proc_ocimem_node =
{
  0x190000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_ocimem_list,
  &route_0x1900000012L_lpass_proc_ocmem_node,
  &route_0x190000001eL_lpass_proc_qdss_stm_node
};
static ul_treeNodeType route_0x190000001eL_lpass_proc_qdss_stm_node =
{
  0x190000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_qdss_stm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x190000001fL_lpass_proc_sdcc_1_node =
{
  0x190000001fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_sdcc_1_list,
  &route_0x190000001aL_lpass_proc_ocimem_node,
  &route_0x1900000027L_lpass_proc_blsp_1_node
};
static ul_treeNodeType route_0x1900000021L_lpass_proc_sdcc_2_node =
{
  0x1900000021ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_sdcc_2_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1900000027L_lpass_proc_blsp_1_node =
{
  0x1900000027ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_blsp_1_list,
  &route_0x1900000021L_lpass_proc_sdcc_2_node,
  &route_0x1900000028L_lpass_proc_usb_hs_node
};
static ul_treeNodeType route_0x1900000028L_lpass_proc_usb_hs_node =
{
  0x1900000028ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_usb_hs_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1900000029L_lpass_proc_pdm_node =
{
  0x1900000029ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_pdm_list,
  &route_0x190000001fL_lpass_proc_sdcc_1_node,
  &route_0x1900000037L_lpass_proc_message_ram_node
};
static ul_treeNodeType route_0x190000002cL_lpass_proc_prng_node =
{
  0x190000002cULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_prng_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1900000033L_lpass_proc_tlmm_node =
{
  0x1900000033ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_tlmm_list,
  &route_0x190000002cL_lpass_proc_prng_node,
  NULL
};
static ul_treeNodeType route_0x1900000037L_lpass_proc_message_ram_node =
{
  0x1900000037ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_message_ram_list,
  &route_0x1900000033L_lpass_proc_tlmm_node,
  &route_0x2100000000L_sdcc_1_ebi_node
};
static ul_treeNodeType route_0x190000003bL_lpass_proc_pmic_arb_node =
{
  0x190000003bULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_pmic_arb_list,
  NULL,
  &route_0x190000004aL_lpass_proc_rpm_node
};
static ul_treeNodeType route_0x190000004aL_lpass_proc_rpm_node =
{
  0x190000004aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_lpass_proc_rpm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2100000000L_sdcc_1_ebi_node =
{
  0x2100000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_ebi_list,
  &route_0x190000003bL_lpass_proc_pmic_arb_node,
  &route_0x210000001eL_sdcc_1_qdss_stm_node
};
static ul_treeNodeType route_0x210000001aL_sdcc_1_ocimem_node =
{
  0x210000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_ocimem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x210000001eL_sdcc_1_qdss_stm_node =
{
  0x210000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_qdss_stm_list,
  &route_0x210000001aL_sdcc_1_ocimem_node,
  NULL
};
static ul_treeNodeType route_0x2100000021L_sdcc_1_sdcc_2_node =
{
  0x2100000021ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_sdcc_2_list,
  &route_0x1900000000L_lpass_proc_ebi_node,
  &route_0x2900000000L_blsp_1_ebi_node
};
static ul_treeNodeType route_0x2100000027L_sdcc_1_blsp_1_node =
{
  0x2100000027ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_blsp_1_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2100000028L_sdcc_1_usb_hs_node =
{
  0x2100000028ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_usb_hs_list,
  &route_0x2100000027L_sdcc_1_blsp_1_node,
  &route_0x2100000037L_sdcc_1_message_ram_node
};
static ul_treeNodeType route_0x2100000033L_sdcc_1_tlmm_node =
{
  0x2100000033ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_tlmm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2100000037L_sdcc_1_message_ram_node =
{
  0x2100000037ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_message_ram_list,
  &route_0x2100000033L_sdcc_1_tlmm_node,
  NULL
};
static ul_treeNodeType route_0x210000003bL_sdcc_1_pmic_arb_node =
{
  0x210000003bULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_pmic_arb_list,
  &route_0x2100000028L_sdcc_1_usb_hs_node,
  &route_0x2300000000L_sdcc_2_ebi_node
};
static ul_treeNodeType route_0x210000004aL_sdcc_1_rpm_node =
{
  0x210000004aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_1_rpm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2300000000L_sdcc_2_ebi_node =
{
  0x2300000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_ebi_list,
  &route_0x210000004aL_sdcc_1_rpm_node,
  &route_0x230000001aL_sdcc_2_ocimem_node
};
static ul_treeNodeType route_0x230000001aL_sdcc_2_ocimem_node =
{
  0x230000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_ocimem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x230000001eL_sdcc_2_qdss_stm_node =
{
  0x230000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_qdss_stm_list,
  &route_0x210000003bL_sdcc_1_pmic_arb_node,
  &route_0x2300000033L_sdcc_2_tlmm_node
};
static ul_treeNodeType route_0x230000001fL_sdcc_2_sdcc_1_node =
{
  0x230000001fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_sdcc_1_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2300000027L_sdcc_2_blsp_1_node =
{
  0x2300000027ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_blsp_1_list,
  &route_0x230000001fL_sdcc_2_sdcc_1_node,
  &route_0x2300000028L_sdcc_2_usb_hs_node
};
static ul_treeNodeType route_0x2300000028L_sdcc_2_usb_hs_node =
{
  0x2300000028ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_usb_hs_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2300000033L_sdcc_2_tlmm_node =
{
  0x2300000033ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_tlmm_list,
  &route_0x2300000027L_sdcc_2_blsp_1_node,
  &route_0x230000003bL_sdcc_2_pmic_arb_node
};
static ul_treeNodeType route_0x2300000037L_sdcc_2_message_ram_node =
{
  0x2300000037ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_message_ram_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x230000003bL_sdcc_2_pmic_arb_node =
{
  0x230000003bULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_pmic_arb_list,
  &route_0x2300000037L_sdcc_2_message_ram_node,
  &route_0x230000004aL_sdcc_2_rpm_node
};
static ul_treeNodeType route_0x230000004aL_sdcc_2_rpm_node =
{
  0x230000004aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sdcc_2_rpm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2900000000L_blsp_1_ebi_node =
{
  0x2900000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_ebi_list,
  &route_0x230000001eL_sdcc_2_qdss_stm_node,
  &route_0x2a0000001aL_usb_hs_ocimem_node
};
static ul_treeNodeType route_0x290000001aL_blsp_1_ocimem_node =
{
  0x290000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_ocimem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x290000001eL_blsp_1_qdss_stm_node =
{
  0x290000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_qdss_stm_list,
  &route_0x290000001aL_blsp_1_ocimem_node,
  &route_0x290000001fL_blsp_1_sdcc_1_node
};
static ul_treeNodeType route_0x290000001fL_blsp_1_sdcc_1_node =
{
  0x290000001fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_sdcc_1_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2900000021L_blsp_1_sdcc_2_node =
{
  0x2900000021ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_sdcc_2_list,
  &route_0x290000001eL_blsp_1_qdss_stm_node,
  &route_0x290000003bL_blsp_1_pmic_arb_node
};
static ul_treeNodeType route_0x2900000028L_blsp_1_usb_hs_node =
{
  0x2900000028ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_usb_hs_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2900000033L_blsp_1_tlmm_node =
{
  0x2900000033ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_tlmm_list,
  &route_0x2900000028L_blsp_1_usb_hs_node,
  &route_0x2900000037L_blsp_1_message_ram_node
};
static ul_treeNodeType route_0x2900000037L_blsp_1_message_ram_node =
{
  0x2900000037ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_message_ram_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x290000003bL_blsp_1_pmic_arb_node =
{
  0x290000003bULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_pmic_arb_list,
  &route_0x2900000033L_blsp_1_tlmm_node,
  &route_0x2a00000000L_usb_hs_ebi_node
};
static ul_treeNodeType route_0x290000004aL_blsp_1_rpm_node =
{
  0x290000004aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_blsp_1_rpm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2a00000000L_usb_hs_ebi_node =
{
  0x2a00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_ebi_list,
  &route_0x290000004aL_blsp_1_rpm_node,
  NULL
};
static ul_treeNodeType route_0x2a0000001aL_usb_hs_ocimem_node =
{
  0x2a0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_ocimem_list,
  &route_0x2900000021L_blsp_1_sdcc_2_node,
  &route_0x2a00000021L_usb_hs_sdcc_2_node
};
static ul_treeNodeType route_0x2a0000001eL_usb_hs_qdss_stm_node =
{
  0x2a0000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_qdss_stm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2a0000001fL_usb_hs_sdcc_1_node =
{
  0x2a0000001fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_sdcc_1_list,
  &route_0x2a0000001eL_usb_hs_qdss_stm_node,
  NULL
};
static ul_treeNodeType route_0x2a00000021L_usb_hs_sdcc_2_node =
{
  0x2a00000021ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_sdcc_2_list,
  &route_0x2a0000001fL_usb_hs_sdcc_1_node,
  &route_0x2a00000037L_usb_hs_message_ram_node
};
static ul_treeNodeType route_0x2a00000027L_usb_hs_blsp_1_node =
{
  0x2a00000027ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_blsp_1_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x2a00000033L_usb_hs_tlmm_node =
{
  0x2a00000033ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_tlmm_list,
  &route_0x2a00000027L_usb_hs_blsp_1_node,
  NULL
};
static ul_treeNodeType route_0x2a00000037L_usb_hs_message_ram_node =
{
  0x2a00000037ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_message_ram_list,
  &route_0x2a00000033L_usb_hs_tlmm_node,
  &route_0x2a0000003bL_usb_hs_pmic_arb_node
};
static ul_treeNodeType route_0x2a0000003bL_usb_hs_pmic_arb_node =
{
  0x2a0000003bULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_pmic_arb_list,
  NULL,
  &route_0x2a0000004aL_usb_hs_rpm_node
};
static ul_treeNodeType route_0x2a0000004aL_usb_hs_rpm_node =
{
  0x2a0000004aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_usb_hs_rpm_list,
  NULL,
  NULL
};

/*============================================================================
                   EXTERNAL DATA DECLARATIONS
============================================================================*/
/* Pointer to the root node */
ul_treeNodeType * route_tree_root = 
  &route_0x2100000021L_sdcc_1_sdcc_2_node;

const uint32 u32ul_arb_master_list_size   = 13;
ul_master_data_type *ul_arb_master_list[] =
{
  &master_bimc_snoc,
  &master_blsp_1,
  &master_cnoc_snoc,
  &master_lpass_ahb,
  &master_lpass_proc,
  &master_periph_snoc,
  &master_pnoc_cfg,
  &master_sdcc_1,
  &master_sdcc_2,
  &master_snoc_bimc,
  &master_snoc_cnoc,
  &master_snoc_pnoc,
  &master_usb_hs,
};

const uint32 u32ul_arb_slave_list_size   = 21;
ul_slave_data_type *ul_arb_slave_list[] =
{
  &slave_bimc_snoc,
  &slave_blsp_1,
  &slave_cnoc_snoc,
  &slave_ebi,
  &slave_message_ram,
  &slave_ocimem,
  &slave_ocmem,
  &slave_pdm,
  &slave_periph_snoc,
  &slave_pmic_arb,
  &slave_pnoc_cfg,
  &slave_prng,
  &slave_qdss_stm,
  &slave_rpm,
  &slave_sdcc_1,
  &slave_sdcc_2,
  &slave_snoc_bimc,
  &slave_snoc_cnoc,
  &slave_snoc_pnoc,
  &slave_tlmm,
  &slave_usb_hs,
};

/* Have to make the array size a const so we can export it */
const uint32 u32ul_arb_clk_node_list_size   = 4;
const char *ul_arb_clock_node_list[] =
{
  "/clk/bimc",
  "/clk/cnoc",
  "/clk/pnoc",
  "/clk/snoc",
};

