#ifndef __HAL_CLK_TEST_H__
#define __HAL_CLK_TEST_H__
/*
==============================================================================

FILE:         HALclkTest.h

DESCRIPTION:
  This file contains the ids for configuring the debug clock circuitry
  for the clock HAL.

==============================================================================

                             Edit History

$Header: //components/rel/core.adsp/2.6.1/systemdrivers/hal/clk/hw/msm8994/inc/HALclkTest.h#1 $

when       who     what, where, why
--------   ---     -----------------------------------------------------------
10/19/11   vs      Created.

==============================================================================
            Copyright (c) 2011 Qualcomm Technologies Incorporated.
                    All Rights Reserved.
                  QUALCOMM Proprietary/GTDR
==============================================================================
*/


/*============================================================================

             DEFINITIONS AND DECLARATIONS FOR MODULE

=============================================================================*/


/* ============================================================================
**    Defines
** ==========================================================================*/

/*
 * Masks used during test clock frequency calculation setup.
 */
#define HAL_CLK_TEST_TYPE_MASK    (0xF0000)
#define HAL_CLK_TEST_SEL_MASK     (0x07FFF)


/*
 * Subsystem domains
 */
#define HAL_CLK_GCC_TEST          (2 << 0x10)
#define HAL_CLK_LPASS_TEST        (3 << 0x10)
#define HAL_CLK_MMSS_TEST         (4 << 0x10)


/*
 * GCC debug clocks.
 */
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_AXI_CLK                                    (HAL_CLK_GCC_TEST | 0x000)
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_USB3_AXI_CLK                               (HAL_CLK_GCC_TEST | 0x001)
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_QDSS_STM_AXI_CLK                           (HAL_CLK_GCC_TEST | 0x002)
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_KPSS_AHB_CLK                               (HAL_CLK_GCC_TEST | 0x003)
#define HAL_CLK_GCC_TEST_GCC_SNOC_CNOC_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x004)
#define HAL_CLK_GCC_TEST_GCC_SNOC_PNOC_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x005)
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_AT_CLK                                     (HAL_CLK_GCC_TEST | 0x006)
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_IPA_AXI_CLK                                (HAL_CLK_GCC_TEST | 0x007)
#define HAL_CLK_GCC_TEST_GCC_CFG_NOC_AHB_CLK                                    (HAL_CLK_GCC_TEST | 0x008)
#define HAL_CLK_GCC_TEST_GCC_CFG_NOC_DDR_CFG_CLK                                (HAL_CLK_GCC_TEST | 0x009)
#define HAL_CLK_GCC_TEST_GCC_CFG_NOC_RPM_AHB_CLK                                (HAL_CLK_GCC_TEST | 0x00A)
#define HAL_CLK_GCC_TEST_GCC_CFG_NOC_TIC_CLK                                    (HAL_CLK_GCC_TEST | 0x00B)
#define HAL_CLK_GCC_TEST_GCC_COPSS_SMMU_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x00C)
#define HAL_CLK_GCC_TEST_GCC_LPSS_SMMU_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x00D)
#define HAL_CLK_GCC_TEST_GCC_PERIPH_NOC_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x010)
#define HAL_CLK_GCC_TEST_GCC_PERIPH_NOC_CFG_AHB_CLK                             (HAL_CLK_GCC_TEST | 0x011)
#define HAL_CLK_GCC_TEST_GCC_PERIPH_NOC_AT_CLK                                  (HAL_CLK_GCC_TEST | 0x012)
#define HAL_CLK_GCC_TEST_GCC_NOC_CONF_XPU_AHB_CLK                               (HAL_CLK_GCC_TEST | 0x018)
#define HAL_CLK_GCC_TEST_GCC_IMEM_AXI_CLK                                       (HAL_CLK_GCC_TEST | 0x020)
#define HAL_CLK_GCC_TEST_GCC_IMEM_CFG_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x021)
#define HAL_CLK_GCC_TEST_GCC_OCMEM_SYS_NOC_AXI_CLK                              (HAL_CLK_GCC_TEST | 0x028)
#define HAL_CLK_GCC_TEST_GCC_OCMEM_NOC_CFG_AHB_CLK                              (HAL_CLK_GCC_TEST | 0x029)
#define HAL_CLK_GCC_TEST_GCC_MMSS_NOC_CFG_AHB_CLK                               (HAL_CLK_GCC_TEST | 0x02A)
#define HAL_CLK_GCC_TEST_GCC_MMSS_NOC_AT_CLK                                    (HAL_CLK_GCC_TEST | 0x02B)
#define HAL_CLK_GCC_TEST_MMSS_GCC_DBG_CLK                                       (HAL_CLK_GCC_TEST | 0x02C)
#define HAL_CLK_GCC_TEST_GCC_MSS_CFG_AHB_CLK                                    (HAL_CLK_GCC_TEST | 0x030)
#define HAL_CLK_GCC_TEST_GCC_MSS_Q6_BIMC_AXI_CLK                                (HAL_CLK_GCC_TEST | 0x031)
#define HAL_CLK_GCC_TEST_MSS_GCC_DBG_CLK                                        (HAL_CLK_GCC_TEST | 0x032)
#define HAL_CLK_GCC_TEST_GCC_QDSS_RBCPR_XPU_AHB_CLK                             (HAL_CLK_GCC_TEST | 0x038)
#define HAL_CLK_GCC_TEST_GCC_QDSS_DAP_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x040)
#define HAL_CLK_GCC_TEST_GCC_QDSS_CFG_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x041)
#define HAL_CLK_GCC_TEST_GCC_QDSS_AT_CLK                                        (HAL_CLK_GCC_TEST | 0x042)
#define HAL_CLK_GCC_TEST_GCC_QDSS_ETR_USB_CLK                                   (HAL_CLK_GCC_TEST | 0x043)
#define HAL_CLK_GCC_TEST_GCC_QDSS_STM_CLK                                       (HAL_CLK_GCC_TEST | 0x044)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TRACECLKIN_CLK                                (HAL_CLK_GCC_TEST | 0x045)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV2_CLK                                (HAL_CLK_GCC_TEST | 0x046)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV3_CLK                                (HAL_CLK_GCC_TEST | 0x048)
#define HAL_CLK_GCC_TEST_GCC_QDSS_DAP_CLK                                       (HAL_CLK_GCC_TEST | 0x049)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV4_CLK                                (HAL_CLK_GCC_TEST | 0x04A)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV8_CLK                                (HAL_CLK_GCC_TEST | 0x04B)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV16_CLK                               (HAL_CLK_GCC_TEST | 0x04C)
#define HAL_CLK_GCC_TEST_GCC_USB30_MASTER_CLK                                   (HAL_CLK_GCC_TEST | 0x050)
#define HAL_CLK_GCC_TEST_GCC_USB30_SLEEP_CLK                                    (HAL_CLK_GCC_TEST | 0x051)
#define HAL_CLK_GCC_TEST_GCC_USB30_MOCK_UTMI_CLK                                (HAL_CLK_GCC_TEST | 0x052)
#define HAL_CLK_GCC_TEST_GCC_USB_HSIC_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x058)
#define HAL_CLK_GCC_TEST_GCC_USB_HSIC_SYSTEM_CLK                                (HAL_CLK_GCC_TEST | 0x059)
#define HAL_CLK_GCC_TEST_GCC_USB_HSIC_CLK                                       (HAL_CLK_GCC_TEST | 0x05A)
#define HAL_CLK_GCC_TEST_GCC_USB_HSIC_IO_CAL_CLK                                (HAL_CLK_GCC_TEST | 0x05B)
#define HAL_CLK_GCC_TEST_GCC_USB_HSIC_IO_CAL_SLEEP_CLK                          (HAL_CLK_GCC_TEST | 0x05C)
#define HAL_CLK_GCC_TEST_GCC_USB_HS_SYSTEM_CLK                                  (HAL_CLK_GCC_TEST | 0x060)
#define HAL_CLK_GCC_TEST_GCC_USB_HS_AHB_CLK                                     (HAL_CLK_GCC_TEST | 0x061)
#define HAL_CLK_GCC_TEST_GCC_USB_HS_INACTIVITY_TIMERS_CLK                       (HAL_CLK_GCC_TEST | 0x062)
#define HAL_CLK_GCC_TEST_GCC_USB2A_PHY_SLEEP_CLK                                (HAL_CLK_GCC_TEST | 0x063)
#define HAL_CLK_GCC_TEST_GCC_USB2B_PHY_SLEEP_CLK                                (HAL_CLK_GCC_TEST | 0x064)
#define HAL_CLK_GCC_TEST_GCC_SDCC1_APPS_CLK                                     (HAL_CLK_GCC_TEST | 0x068)
#define HAL_CLK_GCC_TEST_GCC_SDCC1_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x069)
#define HAL_CLK_GCC_TEST_GCC_SDCC1_INACTIVITY_TIMERS_CLK                        (HAL_CLK_GCC_TEST | 0x06A)
#define HAL_CLK_GCC_TEST_GCC_SDCC2_APPS_CLK                                     (HAL_CLK_GCC_TEST | 0x070)
#define HAL_CLK_GCC_TEST_GCC_SDCC2_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x071)
#define HAL_CLK_GCC_TEST_GCC_SDCC2_INACTIVITY_TIMERS_CLK                        (HAL_CLK_GCC_TEST | 0x072)
#define HAL_CLK_GCC_TEST_GCC_SDCC3_APPS_CLK                                     (HAL_CLK_GCC_TEST | 0x078)
#define HAL_CLK_GCC_TEST_GCC_SDCC3_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x079)
#define HAL_CLK_GCC_TEST_GCC_SDCC3_INACTIVITY_TIMERS_CLK                        (HAL_CLK_GCC_TEST | 0x07A)
#define HAL_CLK_GCC_TEST_GCC_SDCC4_APPS_CLK                                     (HAL_CLK_GCC_TEST | 0x080)
#define HAL_CLK_GCC_TEST_GCC_SDCC4_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x081)
#define HAL_CLK_GCC_TEST_GCC_SDCC4_INACTIVITY_TIMERS_CLK                        (HAL_CLK_GCC_TEST | 0x082)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x088)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_SLEEP_CLK                                    (HAL_CLK_GCC_TEST | 0x089)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP1_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x08A)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP1_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x08B)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART1_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x08C)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART1_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x08D)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP2_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x08E)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP2_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x090)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART2_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x091)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART2_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x092)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP3_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x093)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP3_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x094)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART3_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x095)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART3_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x096)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP4_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x098)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP4_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x099)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART4_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x09A)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART4_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x09B)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP5_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x09C)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP5_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x09D)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART5_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x09E)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART5_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x0A0)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP6_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0A1)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP6_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0A2)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART6_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x0A3)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART6_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x0A4)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x0A8)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_SLEEP_CLK                                    (HAL_CLK_GCC_TEST | 0x0A9)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP1_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0AA)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP1_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0AB)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART1_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x0AC)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART1_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x0AD)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP2_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0AE)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP2_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0B0)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART2_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x0B1)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART2_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x0B2)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP3_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0B3)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP3_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0B4)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART3_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x0B5)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART3_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x0B6)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP4_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0B8)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP4_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0B9)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART4_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x0BA)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART4_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x0BB)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP5_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0BC)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP5_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0BD)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART5_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x0BE)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART5_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x0C0)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP6_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0C1)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP6_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0C2)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART6_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x0C3)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART6_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x0C4)
#define HAL_CLK_GCC_TEST_GCC_PERIPH_XPU_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x0C8)
#define HAL_CLK_GCC_TEST_GCC_PERIPH_NOC_MPU_CFG_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x0C9)
#define HAL_CLK_GCC_TEST_GCC_PDM_AHB_CLK                                        (HAL_CLK_GCC_TEST | 0x0D0)
#define HAL_CLK_GCC_TEST_GCC_PDM_XO4_CLK                                        (HAL_CLK_GCC_TEST | 0x0D1)
#define HAL_CLK_GCC_TEST_GCC_PDM2_CLK                                           (HAL_CLK_GCC_TEST | 0x0D2)
#define HAL_CLK_GCC_TEST_GCC_PRNG_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x0D8)
#define HAL_CLK_GCC_TEST_GCC_BAM_DMA_AHB_CLK                                    (HAL_CLK_GCC_TEST | 0x0E0)
#define HAL_CLK_GCC_TEST_GCC_BAM_DMA_INACTIVITY_TIMERS_CLK                      (HAL_CLK_GCC_TEST | 0x0E1)
#define HAL_CLK_GCC_TEST_GCC_TSIF_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x0E8)
#define HAL_CLK_GCC_TEST_GCC_TSIF_REF_CLK                                       (HAL_CLK_GCC_TEST | 0x0E9)
#define HAL_CLK_GCC_TEST_GCC_TSIF_INACTIVITY_TIMERS_CLK                         (HAL_CLK_GCC_TEST | 0x0EA)
#define HAL_CLK_GCC_TEST_GCC_TCSR_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x0F0)
#define HAL_CLK_GCC_TEST_GCC_BOOT_ROM_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x0F8)
#define HAL_CLK_GCC_TEST_GCC_MSG_RAM_AHB_CLK                                    (HAL_CLK_GCC_TEST | 0x100)
#define HAL_CLK_GCC_TEST_GCC_TLMM_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x108)
#define HAL_CLK_GCC_TEST_GCC_TLMM_CLK                                           (HAL_CLK_GCC_TEST | 0x109)
#define HAL_CLK_GCC_TEST_GCC_MPM_AHB_CLK                                        (HAL_CLK_GCC_TEST | 0x110)
#define HAL_CLK_GCC_TEST_GCC_RPM_PROC_FCLK                                      (HAL_CLK_GCC_TEST | 0x118)
#define HAL_CLK_GCC_TEST_GCC_RPM_PROC_HCLK                                      (HAL_CLK_GCC_TEST | 0x119)
#define HAL_CLK_GCC_TEST_GCC_RPM_BUS_AHB_CLK                                    (HAL_CLK_GCC_TEST | 0x11A)
#define HAL_CLK_GCC_TEST_GCC_RPM_SLEEP_CLK                                      (HAL_CLK_GCC_TEST | 0x11B)
#define HAL_CLK_GCC_TEST_GCC_RPM_TIMER_CLK                                      (HAL_CLK_GCC_TEST | 0x11C)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_ACC_CLK                                   (HAL_CLK_GCC_TEST | 0x120)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x121)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_CLK                                       (HAL_CLK_GCC_TEST | 0x122)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_SENSE_CLK                                 (HAL_CLK_GCC_TEST | 0x123)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_BOOT_ROM_PATCH_CLK                        (HAL_CLK_GCC_TEST | 0x124)
#define HAL_CLK_GCC_TEST_GCC_SPMI_SER_CLK                                       (HAL_CLK_GCC_TEST | 0x128)
#define HAL_CLK_GCC_TEST_GCC_SPMI_CNOC_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x129)
#define HAL_CLK_GCC_TEST_GCC_SPMI_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x12A)
#define HAL_CLK_GCC_TEST_GCC_SPDM_CFG_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x130)
#define HAL_CLK_GCC_TEST_GCC_SPDM_MSTR_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x131)
#define HAL_CLK_GCC_TEST_GCC_SPDM_FF_CLK                                        (HAL_CLK_GCC_TEST | 0x132)
#define HAL_CLK_GCC_TEST_GCC_SPDM_BIMC_CY_CLK                                   (HAL_CLK_GCC_TEST | 0x133)
#define HAL_CLK_GCC_TEST_GCC_SPDM_SNOC_CY_CLK                                   (HAL_CLK_GCC_TEST | 0x134)
#define HAL_CLK_GCC_TEST_GCC_SPDM_PNOC_CY_CLK                                   (HAL_CLK_GCC_TEST | 0x135)
#define HAL_CLK_GCC_TEST_GCC_SPDM_RPM_CY_CLK                                    (HAL_CLK_GCC_TEST | 0x136)
#define HAL_CLK_GCC_TEST_GCC_CE1_CLK                                            (HAL_CLK_GCC_TEST | 0x138)
#define HAL_CLK_GCC_TEST_GCC_CE1_AXI_CLK                                        (HAL_CLK_GCC_TEST | 0x139)
#define HAL_CLK_GCC_TEST_GCC_CE1_AHB_CLK                                        (HAL_CLK_GCC_TEST | 0x13A)
#define HAL_CLK_GCC_TEST_GCC_CE2_CLK                                            (HAL_CLK_GCC_TEST | 0x140)
#define HAL_CLK_GCC_TEST_GCC_CE2_AXI_CLK                                        (HAL_CLK_GCC_TEST | 0x141)
#define HAL_CLK_GCC_TEST_GCC_CE2_AHB_CLK                                        (HAL_CLK_GCC_TEST | 0x142)
#define HAL_CLK_GCC_TEST_GCC_AHB_CLK                                            (HAL_CLK_GCC_TEST | 0x148)
#define HAL_CLK_GCC_TEST_GCC_XO_CLK                                             (HAL_CLK_GCC_TEST | 0x149)
#define HAL_CLK_GCC_TEST_GCC_XO_DIV4_CLK                                        (HAL_CLK_GCC_TEST | 0x14A)
#define HAL_CLK_GCC_TEST_GCC_IM_SLEEP_CLK                                       (HAL_CLK_GCC_TEST | 0x14B)
#define HAL_CLK_GCC_TEST_GCC_BIMC_XO_CLK                                        (HAL_CLK_GCC_TEST | 0x150)
#define HAL_CLK_GCC_TEST_GCC_BIMC_CFG_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x151)
#define HAL_CLK_GCC_TEST_GCC_BIMC_SLEEP_CLK                                     (HAL_CLK_GCC_TEST | 0x152)
#define HAL_CLK_GCC_TEST_GCC_BIMC_SYSNOC_AXI_CLK                                (HAL_CLK_GCC_TEST | 0x153)
#define HAL_CLK_GCC_TEST_GCC_BIMC_CLK                                           (HAL_CLK_GCC_TEST | 0x154)
#define HAL_CLK_GCC_TEST_GCC_BIMC_KPSS_AXI_CLK                                  (HAL_CLK_GCC_TEST | 0x155)
#define HAL_CLK_GCC_TEST_GCC_DDR_DIM_CFG_CLK                                    (HAL_CLK_GCC_TEST | 0x158)
#define HAL_CLK_GCC_TEST_GCC_BIMC_DDR_CPLL0_CLK                                 (HAL_CLK_GCC_TEST | 0x159)
#define HAL_CLK_GCC_TEST_GCC_BIMC_DDR_CPLL1_CLK                                 (HAL_CLK_GCC_TEST | 0x15A)
#define HAL_CLK_GCC_TEST_GCC_DDR_DIM_SLEEP_CLK                                  (HAL_CLK_GCC_TEST | 0x15B)
#define HAL_CLK_GCC_TEST_GCC_BIMC_SMMU_CLK                                      (HAL_CLK_GCC_TEST | 0x15E)
#define HAL_CLK_GCC_TEST_GCC_LPASS_Q6_AXI_CLK                                   (HAL_CLK_GCC_TEST | 0x160)
#define HAL_CLK_GCC_TEST_LPASS_GCC_DBG_CLK                                      (HAL_CLK_GCC_TEST | 0x161)
#define HAL_CLK_GCC_TEST_GCC_LPASS_SYS_NOC_MPORT_CLK                            (HAL_CLK_GCC_TEST | 0x162)
#define HAL_CLK_GCC_TEST_GCC_KPSS_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x168)
#define HAL_CLK_GCC_TEST_GCC_KPSS_AXI_CLK                                       (HAL_CLK_GCC_TEST | 0x169)
#define HAL_CLK_GCC_TEST_KPSS_GCC_DBG_CLK                                       (HAL_CLK_GCC_TEST | 0x16A)
#define HAL_CLK_GCC_TEST_GCC_SNOC_BUS_TIMEOUT0_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x170)
#define HAL_CLK_GCC_TEST_GCC_SNOC_BUS_TIMEOUT2_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x171)
#define HAL_CLK_GCC_TEST_GCC_PNOC_BUS_TIMEOUT0_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x178)
#define HAL_CLK_GCC_TEST_GCC_PNOC_BUS_TIMEOUT1_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x179)
#define HAL_CLK_GCC_TEST_GCC_PNOC_BUS_TIMEOUT2_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x17A)
#define HAL_CLK_GCC_TEST_GCC_PNOC_BUS_TIMEOUT3_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x17B)
#define HAL_CLK_GCC_TEST_GCC_PNOC_BUS_TIMEOUT4_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x17C)
#define HAL_CLK_GCC_TEST_GCC_CNOC_BUS_TIMEOUT0_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x180)
#define HAL_CLK_GCC_TEST_GCC_CNOC_BUS_TIMEOUT1_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x181)
#define HAL_CLK_GCC_TEST_GCC_CNOC_BUS_TIMEOUT2_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x182)
#define HAL_CLK_GCC_TEST_GCC_CNOC_BUS_TIMEOUT3_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x183)
#define HAL_CLK_GCC_TEST_GCC_CNOC_BUS_TIMEOUT4_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x184)
#define HAL_CLK_GCC_TEST_GCC_CNOC_BUS_TIMEOUT5_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x185)
#define HAL_CLK_GCC_TEST_GCC_CNOC_BUS_TIMEOUT6_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x186)
#define HAL_CLK_GCC_TEST_GCC_DEHR_CLK                                           (HAL_CLK_GCC_TEST | 0x188)
#define HAL_CLK_GCC_TEST_GCC_RBCPR_CLK                                          (HAL_CLK_GCC_TEST | 0x190)
#define HAL_CLK_GCC_TEST_GCC_RBCPR_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x191)
#define HAL_CLK_GCC_TEST_WCSS_GCC_DBG_CLK                                       (HAL_CLK_GCC_TEST | 0x198)
#define HAL_CLK_GCC_TEST_USB2_PHY_GCC_ATEST_ULPI_0_CLK                          (HAL_CLK_GCC_TEST | 0x1A0)
#define HAL_CLK_GCC_TEST_USB2_PHY_GCC_ATEST_ULPI_1_CLK                          (HAL_CLK_GCC_TEST | 0x1A8)
#define HAL_CLK_GCC_TEST_USB3_PHY_WRAPPER_GCC_USB3_PIPE_CLK                     (HAL_CLK_GCC_TEST | 0x1B0)
#define HAL_CLK_GCC_TEST_USB2_PHY_WRAPPER_GCC_USB30_UTMI_CLK                    (HAL_CLK_GCC_TEST | 0x1B8)
#define HAL_CLK_GCC_TEST_GPLL0_DTEST                                            (HAL_CLK_GCC_TEST | 0x1C0)
#define HAL_CLK_GCC_TEST_GPLL0_LOCK_DET                                         (HAL_CLK_GCC_TEST | 0x1C1)
#define HAL_CLK_GCC_TEST_GPLL1_DTEST                                            (HAL_CLK_GCC_TEST | 0x1C2)
#define HAL_CLK_GCC_TEST_GPLL1_LOCK_DET                                         (HAL_CLK_GCC_TEST | 0x1C3)
#define HAL_CLK_GCC_TEST_GPLL2_DTEST                                            (HAL_CLK_GCC_TEST | 0x1C4)
#define HAL_CLK_GCC_TEST_GPLL2_LOCK_DET                                         (HAL_CLK_GCC_TEST | 0x1C5)
#define HAL_CLK_GCC_TEST_GPLL3_DTEST                                            (HAL_CLK_GCC_TEST | 0x1C6)
#define HAL_CLK_GCC_TEST_GPLL3_LOCK_DET                                         (HAL_CLK_GCC_TEST | 0x1C7)
#define HAL_CLK_GCC_TEST_MPM_GCC_TEMP_SENSOR_RINGOSC_CLK                        (HAL_CLK_GCC_TEST | 0x1C8)
#define HAL_CLK_GCC_TEST_KPSS_GCC_RINGOSC_CLK                                   (HAL_CLK_GCC_TEST | 0x1D0)
#define HAL_CLK_GCC_TEST_MMPLL0_LV_EARLY                                        (HAL_CLK_GCC_TEST | 0x1D8)


/*
 * LPASS Debug Clocks.
 */
#define HAL_CLK_LPASS_TEST_RESAMPLER_CLK_SRC                            (HAL_CLK_LPASS_TEST | 0x006)
#define HAL_CLK_LPASS_TEST_SPDM_CLK_SRC                                 (HAL_CLK_LPASS_TEST | 0x007)
#define HAL_CLK_LPASS_TEST_Q6SS_BCR_SLP_CLK_SRC                         (HAL_CLK_LPASS_TEST | 0x009)
#define HAL_CLK_LPASS_TEST_SLEEP_CLK_SRC                                (HAL_CLK_LPASS_TEST | 0x00A)
#define HAL_CLK_LPASS_TEST_STM_XO_CLK_SRC                               (HAL_CLK_LPASS_TEST | 0x00B)
#define HAL_CLK_LPASS_TEST_GDSC_XO_CLK_SRC                              (HAL_CLK_LPASS_TEST | 0x00C)
#define HAL_CLK_LPASS_TEST_Q6_XO_CLK_SRC                                (HAL_CLK_LPASS_TEST | 0x00D)
#define HAL_CLK_LPASS_TEST_LPAIF_PCMOE_CLK_SRC                          (HAL_CLK_LPASS_TEST | 0x00F)
#define HAL_CLK_LPASS_TEST_LPASS_Q6CORE_CLK                             (HAL_CLK_LPASS_TEST | 0x010)
#define HAL_CLK_LPASS_TEST_SLIMBUS_CLK_SRC                              (HAL_CLK_LPASS_TEST | 0x011)
#define HAL_CLK_LPASS_TEST_LPAIF_PCM1_CLK_SRC                           (HAL_CLK_LPASS_TEST | 0x012)
#define HAL_CLK_LPASS_TEST_LPAIF_PCM0_CLK_SRC                           (HAL_CLK_LPASS_TEST | 0x013)
#define HAL_CLK_LPASS_TEST_LPAIF_QUAD_CLK_SRC                           (HAL_CLK_LPASS_TEST | 0x014)
#define HAL_CLK_LPASS_TEST_LPAIF_TER_CLK_SRC                            (HAL_CLK_LPASS_TEST | 0x015)
#define HAL_CLK_LPASS_TEST_LPAIF_SEC_CLK_SRC                            (HAL_CLK_LPASS_TEST | 0x016)
#define HAL_CLK_LPASS_TEST_LPAIF_PRI_CLK_SRC                            (HAL_CLK_LPASS_TEST | 0x017)
#define HAL_CLK_LPASS_TEST_LPAIF_SPKR_CLK_SRC                           (HAL_CLK_LPASS_TEST | 0x018)
#define HAL_CLK_LPASS_TEST_AHBFABRIC_CLK_SRC                            (HAL_CLK_LPASS_TEST | 0x01A)
#define HAL_CLK_LPASS_TEST_Q6SS_BCR_SLP_CLK                             (HAL_CLK_LPASS_TEST | 0x01B)
#define HAL_CLK_LPASS_TEST_LPASS_Q6SS_ZMEAS_CLK_SRC                     (HAL_CLK_LPASS_TEST | 0x01C)
#define HAL_CLK_LPASS_TEST_Q6_SPDM_CLK                                  (HAL_CLK_LPASS_TEST | 0x01C)
#define HAL_CLK_LPASS_TEST_Q6SS_AHBM_CLK                                (HAL_CLK_LPASS_TEST | 0x01D)
#define HAL_CLK_LPASS_TEST_Q6SS_AHB_LFABIF_CLK                          (HAL_CLK_LPASS_TEST | 0x01E)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_SYSNOC_CLK                        (HAL_CLK_LPASS_TEST | 0x01F)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_TIMEOUT_CLK                    (HAL_CLK_LPASS_TEST | 0x020)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_SMEM_CLK                       (HAL_CLK_LPASS_TEST | 0x021)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_BR_CLK                         (HAL_CLK_LPASS_TEST | 0x022)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_EFABRIC_SPDMTM_CSR_CLK         (HAL_CLK_LPASS_TEST | 0x024)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_EFABRIC_CLK                    (HAL_CLK_LPASS_TEST | 0x025)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_SECURITY_CLK                   (HAL_CLK_LPASS_TEST | 0x026)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_LCC_CSR_CLK                    (HAL_CLK_LPASS_TEST | 0x027)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_GDSC_XO_CLK                       (HAL_CLK_LPASS_TEST | 0x028)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_BCR_SLP_CLK                       (HAL_CLK_LPASS_TEST | 0x029)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_AVSYNC_CSR_CLK                    (HAL_CLK_LPASS_TEST | 0x02F)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_LPAIF_PCM_DATA_OE_CLK             (HAL_CLK_LPASS_TEST | 0x030)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_LPAIF_CSR_CLK                     (HAL_CLK_LPASS_TEST | 0x037)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_LPAIF_DMA_CLK                     (HAL_CLK_LPASS_TEST | 0x038)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_TIMEOUT_CLK                       (HAL_CLK_LPASS_TEST | 0x039)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_SECURITY_CLK                      (HAL_CLK_LPASS_TEST | 0x03A)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_RESAMPLER_CORE_CLK                (HAL_CLK_LPASS_TEST | 0x03B)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_RESAMPLER_LFABIF_CLK              (HAL_CLK_LPASS_TEST | 0x03C)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_SLIMBUS_CORE_CLK                  (HAL_CLK_LPASS_TEST | 0x03D)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_SLIMBUS_LFABIF_CLK                (HAL_CLK_LPASS_TEST | 0x03E)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_IXFABRIC_SPDMTM_CSR_CLK           (HAL_CLK_LPASS_TEST | 0x041)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_CSR_CLK                           (HAL_CLK_LPASS_TEST | 0x042)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_LPM_CLK                           (HAL_CLK_LPASS_TEST | 0x047)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_DML_CLK                           (HAL_CLK_LPASS_TEST | 0x048)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_IXFABRIC_CLK                      (HAL_CLK_LPASS_TEST | 0x049)
#define HAL_CLK_LPASS_TEST_AVTIMER_XO_CLK_SRC                           (HAL_CLK_LPASS_TEST | 0x050)
#define HAL_CLK_LPASS_TEST_AHB_SPDMTM_CLK                               (HAL_CLK_LPASS_TEST | 0x051)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_AVTIMER_XO_CLK                    (HAL_CLK_LPASS_TEST | 0x052)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_AON_CLK                           (HAL_CLK_LPASS_TEST | 0x056)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_AON_CLK                        (HAL_CLK_LPASS_TEST | 0x057)
#define HAL_CLK_LPASS_TEST_Q6SS_TCM_SLAVE_CLK                           (HAL_CLK_LPASS_TEST | 0x058)
#define HAL_CLK_LPASS_TEST_QUAD_MCLK_CLK_SRC                            (HAL_CLK_LPASS_TEST | 0x05D)
#define HAL_CLK_LPASS_TEST_SLIMBUS2_CLK_SRC                             (HAL_CLK_LPASS_TEST | 0x05D)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_SLIMBUS2_CORE_CLK                 (HAL_CLK_LPASS_TEST | 0x05E)
#define HAL_CLK_LPASS_TEST_TER_MCLK_CLK_SRC                             (HAL_CLK_LPASS_TEST | 0x05E)
#define HAL_CLK_LPASS_TEST_SEC_MCLK_CLK_SRC                             (HAL_CLK_LPASS_TEST | 0x05F)
#define HAL_CLK_LPASS_TEST_PRI_MCLK_CLK_SRC                             (HAL_CLK_LPASS_TEST | 0x060)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_QUAD_MCLK_CLK                  (HAL_CLK_LPASS_TEST | 0x061)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_TER_MCLK_CLK                   (HAL_CLK_LPASS_TEST | 0x062)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_SEC_MCLK_CLK                   (HAL_CLK_LPASS_TEST | 0x063)
#define HAL_CLK_LPASS_TEST_AUDIO_WRAPPER_PRI_MCLK_CLK                   (HAL_CLK_LPASS_TEST | 0x064)
#define HAL_CLK_LPASS_TEST_AUDIO_CORE_SLIMBUS2_LFABIF_CLK               (HAL_CLK_LPASS_TEST | 0x067)

#endif /* !__HAL_CLK_TEST_H__ */

